name: Update and Run Fouri

on:
  schedule:
    - cron: '0 0 */2 * *'  # At twelwe p.m., Run jobs two days later.

jobs:
  update_and_run_fouri:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: pip install --upgrade fouri

    - name: Run fouri command
      run: python3 -m fouri
